### ISSUE TITLE
Issue with functions containing "!"

### ISSUE THREAD

**Issue by GiannisTsagkaropoulos** [m3g/jlcode_example#1]
Hello there, when using functions containing an exclamation mark, the code identifies the exclamation mark as an operator the colours are off. I put the non existent function "apend" in the functions list in the .sty file and compared it with the function "append!" which is also in the list of functions and here's what I got:
<img width="630" alt="Screenshot 2022-03-27 at 3 45 24 PM" src="https://user-images.githubusercontent.com/98717569/160282139-e4dc5754-7917-432f-975e-6e51d4731e05.png">

**Comment by lmiq** [comment]
The issue should be filled in the jlcode repository.
